CREATE
DATABASE IF NOT EXISTS `mo_auth` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
CREATE
DATABASE IF NOT EXISTS `mo_member` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;
CREATE
DATABASE IF NOT EXISTS `mo_admin` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;